Repository redhat-developer/intellij-common-ui-test-library, pull requests merged in 2024-07, with the labels that each got.

#243 feat: Update macos jobs to macos-latest runner
  .github/workflows/dialogs.information_settings.yml
  .github/workflows/dialogs.project_manipulation.yml
  .github/workflows/dialogs.yml
  .github/workflows/mainidewindow.idestatusbar_screenshot.yml
  .github/workflows/mainidewindow.menubar.yml
  .github/workflows/mainidewindow.toolwindowspane.yml
Labels: enhancement

#246 chore: add Dependabot for dependency checks
  .github/dependabot.yml
Labels: enhancement

#239 Added platformType and platformVersion to ProcessBuilder parameters.
  src/main/java/com/redhat/devtools/intellij/commonuitest/UITestRunner.java
Labels: bug

#259 chore: Remove remoteRobotVersion variable to enable dependabot updates
  build.gradle
Labels: dependencies
