Repository redhat-developer/intellij-common-ui-test-library, pull requests merged in 2024-02, with the labels that each got.

#200 fix: Update library for IJ 2023.2
  .github/workflows/dialogs.information_settings.yml
  .github/workflows/dialogs.project_manipulation.yml
  .github/workflows/dialogs.yml
  .github/workflows/mainidewindow.idestatusbar_screenshot.yml
  .github/workflows/mainidewindow.toolwindowspane.yml
  .github/workflows/sonar.yml
  src/main/java/com/redhat/devtools/intellij/commonuitest/fixtures/dialogs/FlatWelcomeFrame.java
  src/main/java/com/redhat/devtools/intellij/commonuitest/fixtures/mainidewindow/toolwindowspane/AbstractToolWinPane.java
  src/main/java/com/redhat/devtools/intellij/commonuitest/fixtures/mainidewindow/toolwindowspane/BuildView.java
  src/main/java/com/redhat/devtools/intellij/commonuitest/utils/constants/ButtonLabels.java
  src/main/java/com/redhat/devtools/intellij/commonuitest/utils/constants/XPathDefinitions.java
  src/main/java/com/redhat/devtools/intellij/commonuitest/utils/project/CreateCloseUtils.java
  src/main/java/com/redhat/devtools/intellij/commonuitest/utils/runner/IntelliJVersion.java
  src/main/java/com/redhat/devtools/intellij/commonuitest/utils/steps/SharedSteps.java
  src/test-project/build.gradle
  src/test-project/gradle.properties
  src/test-project/gradle/wrapper/gradle-wrapper.properties
  src/test-project/src/test/java/com/redhat/devtools/intellij/commonuitest/LibraryTestBase.java
  src/test-project/src/test/java/com/redhat/devtools/intellij/commonuitest/fixtures/test/dialogs/project_manipulation/NewProjectDialogTest.java
  src/test-project/src/test/java/com/redhat/devtools/intellij/commonuitest/fixtures/test/mainidewindow/toolwindowspane/ProjectExplorerTest.java
Labels: bug, enhancement

#185 Fix: Locally built library deleted contents of IdeaProject folder
  README.md
  src/main/java/com/redhat/devtools/intellij/commonuitest/fixtures/dialogs/FlatWelcomeFrame.java
  src/main/java/com/redhat/devtools/intellij/commonuitest/utils/project/CreateCloseUtils.java
  src/test-project/src/test/java/com/redhat/devtools/intellij/commonuitest/fixtures/test/dialogs/FlatWelcomeFrameTest.java
Labels: bug

#208 feat: Added openProjectFromWelcomeDialog method for reopening project
  .github/workflows/mainidewindow.menubar.yml
  src/main/java/com/redhat/devtools/intellij/commonuitest/fixtures/dialogs/FlatWelcomeFrame.java
  src/main/java/com/redhat/devtools/intellij/commonuitest/fixtures/mainidewindow/toolwindowspane/AbstractToolWinPane.java
  src/main/java/com/redhat/devtools/intellij/commonuitest/utils/project/CreateCloseUtils.java
  src/test-project/src/test/java/com/redhat/devtools/intellij/commonuitest/fixtures/test/dialogs/project_manipulation/NewProjectDialogTest.java
  src/test-project/src/test/java/com/redhat/devtools/intellij/commonuitest/fixtures/test/mainidewindow/menubar/MenuBarTest.java
  src/test-project/src/test/java/com/redhat/devtools/intellij/commonuitest/fixtures/test/mainidewindow/toolwindowspane/ProjectExplorerTest.java
Labels: enhancement

#215 feat: Redirecting outputs of intellij instance process improvements
  README.md
  src/main/java/com/redhat/devtools/intellij/commonuitest/UITestRunner.java
  src/test-project/build.gradle
Labels: enhancement
